### ISSUE TITLE
use OffscreenCanvas for workers?

### ISSUE THREAD

**Issue by jimmywarting** [Kaiido/createImageBitmap#1]
>Why isn't the monkey-patch available in web Workers?
>The monkey-patch makes most of its work on an HTMLCanvasElement 2d context, and relies in various places in the ability to have DOM Elements (for instance HTMLImageElements are used to load images from Blobs). Since Web-Workers don't have access to the DOM nor any Elements, the scope of what this monkey-patch could do currently seems too limited to be worth the pain.

**Comment by Kaiido** [comment]
Thanks for the interest.

As of today, only Chromium based browsers support the OffscreenCanvas API.  
These browsers already have (almost) full support of the `createImageBitmap` options, the only feature we could add there is the loading of SVG images from a Blob, except that to be able to load such an image, we need an `HTMLImageElement`, which as said in the quoted text is not available in Workers.  

Firefox does support the WebGLRenderingContext **behind a flag**, but they don't support the OffscreenCanvasRenderingContext2D at all, and they do support the basic syntax of `createImageBitmap`.  
So yes, we could add the resize options in Workers to the users having that flag on in Firefox, by rewriting the resizing part to use the webGL context, but I don't think it's worth the trouble at all.

Not to mention that at least a basic implementation would be necessary anyway for all sources but OffscreenCanvases.

So, while it would have been really great to be able to polyfill this too, I think I'll close this issue for now.
